language: c++
compiler: gcc
sudo: false
matrix:
  include:
    # fully specify builds, include can't dynamically expand matrix entries
    # relative order of sudo and env is important so that addons: is recognized
    - os: linux
      dist: trusty
      sudo: required
      env: TARGET="linux"
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9
          - libxrandr-dev
#    - os: osx
#      compiler: clang
#      env: TARGET="osx"
#    - os: osx
#      compiler: clang
#      env: TARGET="ios"
#    - os: linux
#      sudo: false
#      env: TARGET="android" OPT="armv7"
#      cache:
#        directories:
#        - ~/android-ndk-r10e
#    - os: linux
#      sudo: false
#      env: TARGET="android" OPT="x86"
#      cache:
#        directories:
#        - ~/android-ndk-r10e
  exclude:
    - compiler: gcc
#install:
#    - if [ "$TARGET" == "android" ] || [ "$TARGET" == "linux" ] || [ "$TARGET" == "osx" ]; then
#        scripts/$TARGET/install.sh;
#      fi
script:
    - scripts/$TARGET/build.sh $OPT
git:
    depth: 10
